### ISSUE TITLE
Empty value uses previous value

### ISSUE THREAD

**Issue by joelstransky** [bradjasper/ImportJSON#10]
I'm using this great script to import my Trello history into Google Spreadsheets.
For whatever reason, if a node's value is an emptry string, it uses the previous value for the same node. It continues to do this until it encounters a non-empty value and then repeats the issue.
For instance, if `"/cards/desc"` was one of my queries and returned say, 6 cards, my output might look like (assuming cards 2,3 and 5 have no description):

```
     Data Column Header:
     value from first card
     value from first card
     value from first card
     value from fourth card
     value from fourth card
     value from sixth card
```

**Comment by methodicool** [comment]
I am having the same problem as well! I am trying to parse some json data files and one property includes firstBloodKill which is either true of false. There are 10 players data in the json file, and only one player can get get True while everyone else must get False for firstBloodKills value.This happens when the a value is 0 or false, the cells below it will copy its values would look something like this:

firstBloodKills:
1 False
2 False
3 True
4 data from 3
5 data from 3
6 data from 3
7 data from 3
8 data from 3
9 data from 3
10 data from 3

I really love the importJSON function since I use google for all of my work. There is a 40 man gaming league we are hosting and we need to thorough stats. The only way for me to automatically get those stats and sort them is using this importJSON function.

**Comment by fastfedora** [comment]
I see the problem. At the beginning of defaultTransform_() is the code:

```
  if (!data[row][column]) {
    if (row < 2 || hasOption_(options, "noInherit")) {
      data[row][column] = "";
    } else {
      data[row][column] = data[row-1][column];
    }
  } 
```

The test `!data[row][column]` returns true not only when the column has no data, but also if the value of `data[row][column]` is falsy. This would include the values 0, false and an empty string. Nowadays I try to avoid tests without comparison operators because of this very issue.

The code should be re-written to be:

```
  if (data[row][column] == null) {
    if (row < 2 || hasOption_(options, "noInherit")) {
      data[row][column] = "";
    } else {
      data[row][column] = data[row-1][column];
    }
  } 
```

This will cause the data to only be copied from the previous row when the data is null or undefined (i.e. missing entirely from the current row).

I don't have time to test this right now, so I'm not going to check it into the main codebase yet. If this fix works for either of you, please leave a comment here so I know.

**Comment by methodicool** [comment]
It worked. Thanks so much.

**Comment by tedepstein** [comment]
Thanks for a very useful script!

I had a related problem also traced to the `defaultTransform_()` function.  In my case, some of the source rows were indeed blank:

```
{
  "attendees": [
    {
      "firstName": "Adam",
      "lastName": "Magaluk",
      "github": "https:\/\/github.com\/AdamMagaluk",
      "twitter": "https:\/\/twitter.com\/AdamMagaluk",
      "avatar": "http:\/\/gravatar.com\/avatar\/4f6fc681bb61eb8534abf3877aa49593"
    },
    {
      "firstName": "Adam",
      "lastName": "Bellinson",
      "avatar": "http:\/\/gravatar.com\/avatar\/6f3c82e8e29f17e34c5810a94a216a82"
    },
   ...
 ]
}
```

In the case above, the missing values in the second object were being populated by corresponding values in the first object.  

![image](https://cloud.githubusercontent.com/assets/692813/8578358/54191018-257c-11e5-9369-73ae592a53cd.png)

The quick solution was to use the `noInherit` option.  But I think the intent of "inheritance" is to inherit default values from a parent object, not a preceding sibling object, correct?  In that case, the `else` branch here would need to be modified:

```
  if (!data[row][column]) {
    if (row < 2 || hasOption_(options, "noInherit")) {
      data[row][column] = "";
    } else {
      data[row][column] = data[row-1][column];
    }
  } 
```

You'd want to maintain a stack of ancestor objects, push and pop that stack as you parse the input, and look in that stack for the missing values.

'noInherit' did the trick for me in this case, but there are other cases where users will want true inheritance, not "default to previous," and the only way to get that is to fix the coce.

I'm not a JavaScript developer, so I don't think you'd want me trying to fix this myself.  ;-)  But thought I would point this out here in case it's helpful.

**Comment by bradjasper** [comment]
Fixed this in a commit and created a new issue for the issue you describe @tedepstein

**Comment by roperjonathan** [comment]
I'm having this problem as well. The fields highlighted in red in this screenshots are duplicates. The fields in question are not mandatory and are most of the time left empty.

![spreadsheet](https://user-images.githubusercontent.com/12428853/62525693-c2a3d000-b82f-11e9-8ebc-a8afc7a30460.png)

Is there a way to fix this?
