### ISSUE TITLE
ImportJSON doesn't include null value

### ISSUE THREAD

**Issue by kriskross-ix** [bradjasper/ImportJSON#116]
=ImportJSON("https://data.messari.io/api/v1/assets/" & B109 & "/profile", "/data/name,/data/tagline,/data/organizations/name,/data/people/founding_team/first_name,/data/people/founding_team/last_name,/data/people/founding_team/description,/data/relevant_resources", "noInherit,noTruncate,noHeaders")

"/data/organizations/name" 
works fine when it doesn't have a value

"/data/people/founding_team/first_name"
"/data/people/founding_team/last_name"
"/data/people/founding_team/description" 
doesn't work, only outputs the value when it is not null

Also goes to the next row, not the same with fields: "/data/name,/data/tagline,/data/organizations/name"

**Comment by jvreeken** [comment]
I have the same problem too.
the key is there but the value is null on some values.  
Get the error "Reference does not exist"
#REF!

Would be nice if it would pull in the value as "null"

**Comment by gdesmedt1** [comment]
I managed to solve this by changing a small piece of the code - took me a long time to figure it out tho :) 

On line [426 ](https://github.com/bradjasper/ImportJSON/blob/40cbb9e195721f9d8893d33579f6a1edc0f08f50/ImportJSON.gs#L426)

**Change from this:**
`for (var j = 0; j < data[i].length; j++) {`

**To This**:
`for (var j = 0; j < data[0].length; j++) {`

What happens is that it now references the header (which normally has all fields you recieving from the API) and creating a empty value for values in the array that might be NULL or 'undefined'.

With that change, the code will handle NULL values (especially when at the end of a row) :)

_@bradjasper - is it possible to update the code with the above?_

Regards,
G

**Comment by bradjasper** [comment]
Done, thanks @gdesmedt1!

**Comment by tonylangley** [comment]
I think the version (on line 4) needs updating to 1.6.0

**Comment by gonzas** [comment]
Please, I need some help here, since I am not a developer:

How can I get a string named "null" in the result ? 
I am using version 1.6.0.

In my JSON input I would like to get the "Employees" value as a part of the output:
{"address":"1167 Kensington Crescent NW","employees":null,"exchange":"NASDAQ"}

And I am calling in google sheets like this:

=if(isblank(A8),"",importJson(concatenate(Aux!$B$14,"/stable/stock/",A10,"/company?filter=address,employees,exchange&token=",Aux!$B$15),,"debugLocation"))

with this output:
[0,0]Address	[0,1]Exchange
[1,0]1167 Kensington Crescent NW	[1,1]NASDAQ

Instead of this:

[0,0]Address	[0,1] Employees [0,2]Exchange
[1,0]1167 Kensington Crescent NW [1,1] null	[1,2]NASDAQ

Thank you !
