### ISSUE TITLE
Urgent - Time Sensitive | Send POST JSON Body with URL to retrieve data

### ISSUE THREAD

**Issue by XxLilBoPeepsxX** [bradjasper/ImportJSON#205]
Hello! I am working on a time-sensitive project for a client that requires sending a POST request with JSON data inside of said request to a URL, and then parsing and inserting the data into the Google Spreadsheet. I have been unfortunately unable to determine a way to do this and was hoping that you would be able to help, can someone tell me what I am missing or what function to use, or how to modify the code so that I can successfully do like so? I would greatly appreciate it! Thank you!

**Comment by jallen92** [comment]
I just ran into this issue as well. I solved it by having the JSON request body data live in its own cell (on a different sheet to avoid overwriting), and then passed that cell as the `payload` argument in the `ImportJSONViaPost` spreadsheet function.

Here's how my working formula looks:

`=ImportJSONViaPost("https://foo.bar.us-east-1.amazonaws.com/prod/search", Sheet2!A1, "contentType=application/json")`

And my `Sheet2!A1` cell contains the raw JSON payload: `{"queryStr":"foo bar","category":"location","from":0}`

If your request is more complex then I recommend taking a look at the following:
- [Source code for ImportJSONViaPost](https://github.com/bradjasper/ImportJSON/blob/ae64c908b82cc8cf8840e176930ad937883fbe37/ImportJSON.gs#L74-L136)
- [Source code for ImportJSONAdvanced](https://github.com/bradjasper/ImportJSON/blob/ae64c908b82cc8cf8840e176930ad937883fbe37/ImportJSON.gs#L179-L225)
- [Documentation for UrlFetchApp](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetchurl,-params) which is used by all the `ImportJSON` functions and has an example for making a POST request with a JSON payload.

I think the underlying issue is that `ImportJSON` just passes the payload unchanged to the request (i.e. as a string if you're manually typing it out).

I'd imagine you could also solve this by modifying the `ImportJSONViaPost` function to parse the string into JSON [on line 125](https://github.com/bradjasper/ImportJSON/blob/ae64c908b82cc8cf8840e176930ad937883fbe37/ImportJSON.gs#L125).

```javascript
  if (postOptions["contentType"] == "application/json") {
    postOptions["payload"] = JSON.parse(payload);
  }
```

That would then allow you to pass the JSON payload as a string to the spreadsheet function. (But would then no longer allow you to pass data that's already formatted as JSON).

Bit of a messy way to go about it but it should work if you do want to pass the JSON payload as a string.

Depending on what you're trying to do it may better to just spend the time to add the additional logic to handle payload data that's formatted as either a string or JSON.

**Comment by XxLilBoPeepsxX** [comment]
Let me try it out, thank you so much!

**Comment by XxLilBoPeepsxX** [comment]
@jallen92 So how can I include cookies with the POST request, if I can ask?

**Comment by XxLilBoPeepsxX** [comment]
And as an update, I am trying this out, but I'm encountering the same issue I've been experiencing before -  the POST request is sent, but the JSON payload is not being interpreted with it, it is just returning all data that is available from the endpoint instead of what I am requesting from it based on the JSON payload. Any thoughts?
